INSERT INTO tx_adventskalender_domain_model_door (pid, day, title, description, content, is_active, tstamp, crdate, hidden, deleted, sorting) VALUES
(1, 1, '1. Dezember', 'Willkommen im Adventskalender!', '<p>Frohe Weihnachtszeit! Das erste Türchen ist geöffnet.</p>', 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), 0, 0, 1),
(1, 2, '2. Dezember', 'Zweites Türchen', '<p>Ein neuer Tag, eine neue Überraschung!</p>', 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), 0, 0, 2),
(1, 3, '3. Dezember', 'Drittes Türchen', '<p>Genieße die Adventszeit!</p>', 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), 0, 0, 3),
(1, 4, '4. Dezember', 'Viertes Türchen', '<p>Noch 20 Tage bis Weihnachten!</p>', 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), 0, 0, 4),
(1, 5, '5. Dezember', 'Fünftes Türchen', '<p>Der Nikolaus kommt bald!</p>', 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), 0, 0, 5),
(1, 6, '6. Dezember', 'Nikolaustag', '<p>Heute ist Nikolaus! Hast du deine Schuhe geputzt?</p>', 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), 0, 0, 6),
(1, 7, '7. Dezember', 'Siebtes Türchen', '<p>Die erste Adventswoche ist fast vorbei.</p>', 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), 0, 0, 7),
(1, 8, '8. Dezember', 'Achtes Türchen', '<p>Zweite Adventswoche beginnt!</p>', 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), 0, 0, 8),
(1, 9, '9. Dezember', 'Neuntes Türchen', '<p>Genieße die besinnliche Zeit.</p>', 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), 0, 0, 9),
(1, 10, '10. Dezember', 'Zehntes Türchen', '<p>Nur noch 14 Tage bis Heiligabend!</p>', 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), 0, 0, 10),
(1, 11, '11. Dezember', 'Elftes Türchen', '<p>Die Hälfte ist geschafft!</p>', 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), 0, 0, 11),
(1, 12, '12. Dezember', 'Zwölftes Türchen', '<p>Mitte des Advents!</p>', 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), 0, 0, 12),
(1, 13, '13. Dezember', 'Dreizehntes Türchen', '<p>Lucia-Tag wird heute gefeiert.</p>', 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), 0, 0, 13),
(1, 14, '14. Dezember', 'Vierzehntes Türchen', '<p>Noch 10 Tage bis Weihnachten!</p>', 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), 0, 0, 14),
(1, 15, '15. Dezember', 'Fünfzehntes Türchen', '<p>Dritte Adventswoche!</p>', 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), 0, 0, 15),
(1, 16, '16. Dezember', 'Sechzehntes Türchen', '<p>Die Vorfreude steigt!</p>', 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), 0, 0, 16),
(1, 17, '17. Dezember', 'Siebzehntes Türchen', '<p>Eine Woche bis Heiligabend!</p>', 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), 0, 0, 17),
(1, 18, '18. Dezember', 'Achtzehntes Türchen', '<p>Die Zeit rennt!</p>', 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), 0, 0, 18),
(1, 19, '19. Dezember', 'Neunzehntes Türchen', '<p>Nur noch 5 Tage!</p>', 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), 0, 0, 19),
(1, 20, '20. Dezember', 'Zwanzigstes Türchen', '<p>4. Advent steht bevor!</p>', 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), 0, 0, 20),
(1, 21, '21. Dezember', 'Einundzwanzigstes Türchen', '<p>Winteranfang!</p>', 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), 0, 0, 21),
(1, 22, '22. Dezember', 'Zweiundzwanzigstes Türchen', '<p>Nur noch 2 Tage!</p>', 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), 0, 0, 22),
(1, 23, '23. Dezember', 'Dreiundzwanzigstes Türchen', '<p>Morgen ist Heiligabend!</p>', 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), 0, 0, 23),
(1, 24, 'Heiligabend', 'Das letzte Türchen!', '<p>🎄 Frohe Weihnachten! Das Warten hat ein Ende! 🎅</p>', 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), 0, 0, 24);
